# -*- mode: python ; coding: utf-8 -*-

import sys
from pathlib import Path

block_cipher = None

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('app/resources/icon.svg', 'app/resources'),
        ('app/resources/postgresql.svg', 'app/resources'),
        ('app/resources/mysql.svg', 'app/resources'),
        ('app/resources/sqlite.svg', 'app/resources'),
        ('app/resources/sqlserver.svg', 'app/resources'),
        ('app/resources/table.svg', 'app/resources'),
        ('app/resources/view.svg', 'app/resources'),
        ('app/resources/routine.svg', 'app/resources'),
        ('app/resources/trigger.svg', 'app/resources'),
        ('app/resources/connection.svg', 'app/resources'),
        ('app/resources/database.svg', 'app/resources'),
        ('app/resources/run.svg', 'app/resources'),
        ('app/resources/stop.svg', 'app/resources'),
        ('app/resources/save.svg', 'app/resources'),
        ('app/resources/export.svg', 'app/resources'),
        ('app/resources/new_query.svg', 'app/resources'),
        ('app/resources/refresh.svg', 'app/resources'),
        ('app/resources/delete.svg', 'app/resources'),
    ],
    hiddenimports=[
        'app',
        'app.db_drivers',
        'app.db_drivers.base',
        'app.db_drivers.postgres',
        'app.db_drivers.mysql',
        'app.db_drivers.sqlite',
        'app.db_drivers.sqlserver',
        'app.ui',
        'app.ui.theme',
        'app.ui.connection_dialog',
        'installer',
        'installer.manager',
        'sqlparse',
        'sqlparse.filters',
        'sqlparse.filters.align_indent',
        'sqlparse.filters.output',
        'sqlparse.filters.reindent',
        'sqlparse.filters.right_margin',
        'sqlparse.filters.tokens',
        'sqlparse.keywords',
        'sqlparse.lexer',
        'sqlparse.engine',
        'sqlparse.exceptions',
        'sqlparse.formatter',
        'sqlparse.sql',
        'sqlparse.tokens',
        'sqlparse.utils',
        'psycopg2',
        'psycopg2._range',
        'psycopg2._ipaddress',
        'psycopg2._json',
        'mysql.connector',
        'mysql.connector.locales',
        'mysql.connector.locales.eng',
        'pymssql',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'tkinter',
        'matplotlib',
        'numpy',
        'PIL',
        'Pillow',
        'scipy',
        'pandas',
        'notebook',
        'jupyter',
        'test',
        'distutils',
    ],
    noarchive=False,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='database-manager',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)
